name: Compile LaTeX and Deploy to Pages

on:
  push:
    branches:
      - main  # Triggers the workflow every time you push to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: resume.tex 
      - name: Prepare deployment directory
        run: |
          mkdir public
          cp index.html public/
          cp resume.pdf public/  # Move compiled PDF into the deployment folder

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
